### ISSUE TITLE
Adjust set of questions in 01 lesson to match objectives of other lessons

### ISSUE THREAD

**Issue by tracykteal** [datacarpentry/r-spatial-data-management-intro#1]
We want to start lesson 01 with a set of questions we're going to address. To figure out what those are, we need to see what the other lessons are doing and adjust.

**Comment by mjones01** [comment]
The new redesign of the Intro/ Data Management lessons have done just this! (We hope).  Closing issue -- feel free to create new issues about specific deficiencies/ mis-alignment.
