### ISSUE TITLE
Possible video for Science Questions Lesson

### ISSUE THREAD

**Issue by mjones01** [datacarpentry/r-spatial-data-management-intro#19]
This video is at a very basic level and plugs PBB at the end but it does connect plants to climate change.  Depending on how the science questions lesson is written this could be a useful video: 
Changing Climates: What's a Plant to Do?
https://www.youtube.com/watch?v=W_K8bd139iw

**Comment by lwasser** [comment]
i suggest that we close this issue as well given the learning objectives of this lesson set has shifted to a broader spatial data focus even though it has a plants and climate theme associated with the data!
