### ISSUE TITLE
Create github.io page for this repo

### ISSUE THREAD

**Issue by mjones01** [datacarpentry/r-spatial-data-management-intro#3]

**Comment by lwasser** [comment]
http://data-lessons.github.io/NEON-R-Spatial-Data-Intro/ any gh-pages branch has a site. we just need to adjust the landing page, etc. and ensure .md files are in the _posts dir.

I'd like to change hte name though to spatio-temporal-data or something more meaningful and representative of the overall series of lessons :)

**Comment by mjones01** [comment]
How about: Intro to Spatial Data & Data Management  (NEON-R-Spatial-Data-Management-Intro) to parallel the unit title in gDoc? 

I need to sign is as NEON Data Skills and can then assign myself privileges to make edits & can add the github.io page.  I just don't have access yet.

**Comment by tracykteal** [comment]
I like the 'Data Management Intro' title. @mjones01Is it the NEON site you need privileges on or do you need privileges on the data-skills repo?

**Comment by mjones01** [comment]
@tracykteal RE access: just this repo for mjones01

RE Name:  Retaining something about Spatial Data, not just Data Management, in the title is important in my opinion as the lessons (see PR https://github.com/data-lessons/NEON-R-Spatial-Data-Intro/pull/4) are primarily about understanding spatial data and some about data management (For lessons that might be worth adding see issues #6 and #5 ).

**Comment by lwasser** [comment]
Hi All - this needs to be spatio-temporal data! Also this isn't necessarily all about data management. it's also about data literacy given these data require knowledge of many spatial- specific concepts/

**Comment by lwasser** [comment]
Intro-to-Spatio-temporal-data-best-practices

Intro-to-SpatioTemporal-data-and-management

**Comment by mjones01** [comment]
I think we should separate out the repo name discussion (which I think this is focused on) and the unit/ lesson series name.   The two should be similar but I think the lesson series name needs to be more complete while the repo name needs all the key words but can be a bit inelegant (and not get crazy long). 

How about: 
Repo: NEON-R-Spatio-Temporal-Data-and-Management  (I'd cut the 'and' before I can see now that is confusing)  
Unit/Lesson Series:  Intro to Spatio-temporal Data and Data Management Best Practices

**Comment by lwasser** [comment]
yup - i think we need an intro so it's clear its an overview series. so...
NEON-R-Spatio-Temporal-Data-and-Management-Intro

OR 

NEON-R-Intro-To-Spatio-Temporal-Data-and-Management

phew
i'm good with the lesson as i need to dig into content :)

**Comment by mjones01** [comment]
Repo name is changed.  And github.io is set up.  Pages will build after my PR before leaving tonight.
