### ISSUE TITLE
intro link is broken

### ISSUE THREAD

**Issue by maneesha** [datacarpentry/r-spatial-data-management-intro#32]
This link is broken: http://datacarpentry.github.io/NEON-R-Spatio-Temporal-Data-and-Management-Intro/

**Comment by maneesha** [comment]
@lwasser @jsta  @tracykteal   Checking in on this issue from last month.  Can we please fix this? It's been brought up to me by a few people.

**Comment by lwasser** [comment]
hey @maneesha looks like the repo name changed -- http://www.datacarpentry.org/r-spatial-data-management-intro/ this works. i think the config file will need an update and then it will all be working. i haven't been working on these lessons as we dont' seem to have much help in building them out! i need to chat with @tracykteal about this!

**Comment by lwasser** [comment]
this should fix the styles not loading

5210999d3ef37cb7c8377c55762676f8894e6afb

**Comment by lwasser** [comment]
you may need to fix the website now to just link to the correct url! @maneesha  but these lessons need a ton of work. i've actually redone some of them for my class this semester and could contribute back if someone else is working on them too.

**Comment by jsta** [comment]
I'm not really sure what the best course of action is here. It would be good to convert all of this material away from `sp` and towards the `sf` package ( https://github.com/datacarpentry/R-spatial-raster-vector-lesson/issues/92). I would be interested in doing that but `sf` is still a work in progress (at least I have run into a few deal-breaking issues having to do with `sf` x `ggplot`).

**Comment by lwasser** [comment]
i agree @jsta i've been playing with SF too and have run into the same thing. In fact i'm working on the CRS lessons NOW and just tried sf and there are a lot of bugs still as nice as i know it will be. I don't want to teach with it until the bugs are ironed out. i just had geom_sf fail because it couldn't be found - and that required dev versions of the packages to be installed... ugh...

**Comment by lwasser** [comment]
note that the CRS lessons here do use ggplot. but you have to fortify() each time. and the code is messy - i'm cleaning that up now for my class. the other lessons all use old school sp but it works.

**Comment by maneesha** [comment]
So @lwasser @jsta @tracykteal  Looks like this conversation digressed a bit from just a broken link to being about the lessons themselves needing a lot of work.  We do get people asking about them.  Can we put them on hiatus if they are not ready for primetime? Especially if Leah is saying she doesn't want to teach with them herself until the bugs get worked out -- I can't expect other instructors to be comfortable with the lessons themselves.

**Comment by jsta** [comment]
The link works now and it looks like discussion has moved to issue 33.
